### ISSUE TITLE
jetty launch webapp project error

### ISSUE THREAD

**Issue by efsn** [guikeller/jetty-runner#53]
The project has multiple webapp module, I create a runner configuration in Jetty Runner, fill in webapp, classes Folders option, I cann't find the dependency classpath option. When I run the configuration, the SLF4J error will interrupt the process. Actually when launch jetty runner, it will scan other webapp module  lib folder.

Below is the error message, I just launch tms-manage webapp with module library configuration.
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/E:/HU/ws/tms/tms-dao/src/lib/slf4j-log4j12-1.4.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/E:/HU/ws/tms/tms-itg/WebContent/WEB-INF/lib/slf4j-log4j12-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/E:/HU/ws/tms/tms-manage/WebContent/WEB-INF/lib/slf4j-log4j12-1.5.8.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/E:/HU/ws/tms/tms-gateway/WebContent/WEB-INF/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/E:/HU/ws/tms/tms-gateway/WebContent/WEB-INF/lib/slf4j-log4j12-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/E:/HU/ws/tms/tms-api/WebContent/WEB-INF/lib/slf4j-log4j12-1.4.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
Exception in thread "main" java.lang.NoSuchMethodError: org.slf4j.helpers.MessageFormatter.arrayFormat(Ljava/lang/String;[Ljava/lang/Object;)Lorg/slf4j/helpers/FormattingTuple;
```
Jetty Runner 1.2.1
JRE 1.8

How to solve this, thank you.

**Comment by guikeller** [comment]
Hi @efsn 

Your project (tms-web?) has module dependencies - eg: tms-dao, tms-api, tms-etc..
These are defining / using different versions of the same library (slf4j):
```
tms-dao uses: slf4j-log4j12-**1.4.2**.jar
tms-itg uses: slf4j-log4j12-**1.7.6**.jar
tms-manage uses: slf4j-log4j12-**1.5.8**.jar
tms-gateway uses: **logback-classic-1.2.3.jar**
tms-gateway uses: slf4j-log4j12-**1.7.6**.jar
tms-api uses: slf4j-log4j12-**1.4.2**.jar
```

All of the jars above have an implementation for:
_org.slf4j.impl.StaticLoggerBinder.class_

The SL4J does not like it because does not know which one to use and complains:
**Class path contains multiple SLF4J bindings**
_See http://www.slf4j.org/codes.html#multiple_bindings for an explanation._

We can conclude that this is a classpath issue with your project.
If you use the same slf4j version throughout your projects the problem will go away.

Best of luck! Cheers 👍
