### ISSUE TITLE
Without web.xml, @WebServlet not work

### ISSUE THREAD

**Issue by baishui2004** [guikeller/jetty-runner#55]
Hey, I use jetty run, version 1.2.1 https://plugins.jetbrains.com/plugin/7505-idea-jetty-runner, and without web.xml, but @WebServlet not work, is that? Thank you.

**Comment by guikeller** [comment]
How can I reproduce the problem? 😺

**Comment by miclefebvre** [comment]
For me, it shows the directory listing instead of loading the servlets. Does using annotation instead of web.xml is supported ?

**Comment by guikeller** [comment]
Hi @miclefebvre,

I did not cater to that, so the answer is no.
You will need a web.xml in place to get the plugin to work at this stage.

If you could create a bare minimum project sample where I can reproduce the issue I will make a fix for it. Otherwise, a Pull Request is always welcome.

Cheers, 
Gui
