### ISSUE TITLE
Hi,I am 贺春阳

### ISSUE THREAD

**Issue by chunyanghe** [guikeller/jetty-runner#66]
Sorry,long time no see,I am 贺春阳，Cloud you tell me the detail of the jetty runner when I ask you in page
[jetty-runner](https://plugins.jetbrains.com/plugin/7505-idea-jetty-runner)

**Comment by guikeller** [comment]
Hi @chunyanghe 

The problem lies because of the following scenario below:

You are adding the jars to the classpath and that is recognised by the "plugin".
Which then adds to the Jetty classpath for you - if it is in your classpath it is needed to run.

During the startup Jetty also looks for jars under "WEB-INF/lib" - default servlet container behaviour.
Your jars happen to live under "WEB-INF/lib", so Jetty adds them a second time - causing problems.

Have a look on this link below, hope this helps:
https://www.jetbrains.com/help/idea/creating-and-managing-modules.html

Cheers,
Gui

**Comment by chunyanghe** [comment]
> Hi @chunyanghe
> 
> The problem lies because of the following scenario below:
> 
> You are adding the jars to the classpath and that is recognised by the "plugin".
> Which then adds to the Jetty classpath for you - if it is in your classpath it is needed to run.
> 
> During the startup Jetty also looks for jars under "WEB-INF/lib" - default servlet container behaviour.
> Your jars happen to live under "WEB-INF/lib", so Jetty adds them a second time - causing problems.
> 
> Have a look on this link below, hope this helps:
> https://www.jetbrains.com/help/idea/creating-and-managing-modules.html
> 
> If you have any ideas on how that could be fixed a PR is welcome.
> 
> Cheers,
> Gui



> Hi @chunyanghe
> 
> The problem lies because of the following scenario below:
> 
> You are adding the jars to the classpath and that is recognised by the "plugin".
> Which then adds to the Jetty classpath for you - if it is in your classpath it is needed to run.
> 
> During the startup Jetty also looks for jars under "WEB-INF/lib" - default servlet container behaviour.
> Your jars happen to live under "WEB-INF/lib", so Jetty adds them a second time - causing problems.
> 
> Have a look on this link below, hope this helps:
> https://www.jetbrains.com/help/idea/creating-and-managing-modules.html
> 
> If you have any ideas on how that could be fixed a PR is welcome.
> 
> Cheers,
> Gui

It is helpful to me, thank you for  your advice !

**Comment by guikeller** [comment]
The comment above also addresses: Issue #64
